name: 'Setup PlantUML.nvim Development Environment'
description: 'Common setup steps for plantuml.nvim development and testing - reusable composite action'
author: 'plantuml.nvim'

inputs:
  skip-playwright:
    description: 'Skip Playwright installation (for lighter setups)'
    required: false
    default: 'false'
  skip-virtual-display:
    description: 'Skip virtual display setup (for non-browser testing)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl \
          wget \
          unzip \
          xvfb \
          nodejs \
          npm
          
    - name: Install Neovim
      shell: bash
      run: |
        # Add Neovim PPA for latest version
        sudo add-apt-repository ppa:neovim-ppa/unstable -y
        sudo apt-get update
        sudo apt-get install -y neovim
        
        # Verify installation
        nvim --version
        
    - name: Verify Neovim installation
      shell: bash
      run: |
        nvim --version
        which nvim
        # Ensure Neovim is working properly
        nvim --headless -c "echo 'Neovim is working'" -c "qall!"
        
    - name: Install Node.js dependencies
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          npm install
        else
          echo "No package.json found, skipping npm install"
        fi
        
    - name: Install Playwright
      if: inputs.skip-playwright != 'true'
      shell: bash
      run: |
        npx playwright install chromium --with-deps
        
    - name: Setup test environment
      shell: bash
      run: |
        if [ -f "./tests/setup-test-env.sh" ]; then
          ./tests/setup-test-env.sh
        else
          echo "No setup-test-env.sh found, skipping test environment setup"
        fi
        
    - name: Start virtual display for browser tests
      if: inputs.skip-virtual-display != 'true'
      shell: bash
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Verify setup completion
      shell: bash
      run: |
        echo "Development environment setup complete!"
        echo "Available tools:"
        echo "- Neovim: $(nvim --version | head -1)"
        echo "- Node.js: $(node --version)"
        echo "- npm: $(npm --version)"
        if [ "${{ inputs.skip-playwright }}" != "true" ]; then
          echo "- Playwright: $(npx playwright --version 2>/dev/null || echo 'Not installed')"
        fi
        if [ "${{ inputs.skip-virtual-display }}" != "true" ]; then
          echo "- Display: ${DISPLAY:-'Not set'}"
        fi
        echo ""
        echo "Available test scripts:"
        find ./tests -name "test-*.sh" -type f 2>/dev/null | sort || echo "No test scripts found"