name: Functional Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl \
          wget \
          unzip \
          xvfb \
          nodejs \
          npm
          
    - name: Install Neovim
      run: |
        # Get the latest release URL from GitHub API
        LATEST_URL=$(curl -s https://api.github.com/repos/neovim/neovim/releases/latest | grep -o 'https://github.com/neovim/neovim/releases/download/[^"]*nvim-linux64.tar.gz')
        echo "Downloading Neovim from: $LATEST_URL"
        
        # Download and verify the file
        curl -L "$LATEST_URL" -o nvim-linux64.tar.gz
        if [ ! -f nvim-linux64.tar.gz ] || [ $(stat -c%s nvim-linux64.tar.gz) -lt 1000000 ]; then
          echo "Download failed or file too small"
          exit 1
        fi
        
        # Verify it's a valid gzip file
        if ! gzip -t nvim-linux64.tar.gz; then
          echo "Downloaded file is not a valid gzip archive"
          exit 1
        fi
        
        # Extract and install
        sudo tar -C /opt -xzf nvim-linux64.tar.gz
        sudo ln -sf /opt/nvim-linux64/bin/nvim /usr/local/bin/nvim
        # Add to PATH for current job
        echo "/opt/nvim-linux64/bin" >> $GITHUB_PATH
        
    - name: Verify Neovim installation
      run: |
        nvim --version
        which nvim
        # Ensure Neovim is working properly
        nvim --headless -c "echo 'Neovim is working'" -c "qall!"
        
    - name: Install Playwright
      run: |
        npm install
        npx playwright install chromium --with-deps
        
    - name: Setup test environment
      run: |
        chmod +x ./tests/setup-test-env.sh
        ./tests/setup-test-env.sh
        
    - name: Run plugin loading tests
      run: |
        chmod +x ./tests/test-plugin-loading.sh
        ./tests/test-plugin-loading.sh
        
    - name: Start virtual display for browser tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Run HTTP server tests
      run: |
        chmod +x ./tests/test-http-server.sh
        ./tests/test-http-server.sh
        
    - name: Run WebSocket tests
      run: |
        chmod +x ./tests/test-websocket.sh
        ./tests/test-websocket.sh
        
    - name: Run PlantUML processing tests
      run: |
        chmod +x ./tests/test-plantuml-processing.sh
        ./tests/test-plantuml-processing.sh
        
    - name: Run browser UI interaction tests
      run: |
        chmod +x ./tests/test-browser-ui.sh
        ./tests/test-browser-ui.sh
        
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          tests/logs/
          tests/screenshots/
        retention-days: 7