name: Functional Tests (Using Copilot Setup)

on:
  workflow_dispatch:  # Manual trigger to test the new setup

jobs:
  functional-tests-with-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup development environment
      uses: ./.github/actions/setup-dev-env
        
    - name: Run plugin loading tests
      run: ./tests/test-plugin-loading.sh
        
    - name: Run HTTP server tests
      run: ./tests/test-http-server.sh
        
    - name: Run WebSocket tests
      run: ./tests/test-websocket.sh
        
    - name: Run PlantUML processing tests
      run: ./tests/test-plantuml-processing.sh
        
    - name: Run browser UI interaction tests
      run: ./tests/test-browser-ui.sh
        
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-copilot-setup
        path: |
          tests/logs/
          tests/screenshots/
        retention-days: 7